cache-dir = "/var/cache/gddns"

[hosts]

  [hosts."noip-subdomain.example.com"]
  username = "NoIPUsername"
  password = "NoIPP@ssword2048"
  dyndns_url = "https://dynupdate.no-ip.com/nic/update"

  [hosts."google-subdomain.example.com"]
  username = "HExV0aKG0TvckGKh"
  password = "F4WmsCLfTGXnR1j5"
  dyndns_url = "https://domains.google.com/nic/update"
