cache-dir = "/var/cache/gddns"
daemon-poll-interval = 300

[hosts]

# Add your own host config here
# Google Domains example
#   [hosts."google-subdomain.example.com"]
#   username = "HExV0aKG0TvckGKh"
#   password = "F4WmsCLfTGXnR1j5"
#   dyndns-url = "https://domains.google.com/nic/update"
#
# NoIP example
#   [hosts."noip-subdomain.example.com"]
#   username = "NoIPUsername"
#   password = "NoIPP@ssword2048"
#   dyndns-url = "https://dynupdate.no-ip.com/nic/update"
#   server-backoff = 30
