cache-dir = "/var/cache/gddns"
daemon-poll-interval = 300

[hosts]

# Add your own host config here
# deSEC example
#   [hosts."desec-subdomain.example.com"]
#   token = "iAZzo1noWZaReZhafDhAJRHFSm2s"
#   dyndns-url = "https://update.dedyn.io"
#
# NoIP example
#   [hosts."noip-subdomain.example.com"]
#   username = "NoIPUsername"
#   password = "NoIPP@ssword2048"
#   dyndns-url = "https://dynupdate.no-ip.com/nic/update"
#   server-backoff = 30
